[ballerina.http.accessLogConfig]
# Enable printing access logs in console. Default is false.
console = true
# Specify the file path to save the access logs. This is optional.  
path = "testAccessLog.txt"
