name: Test Distribution

on:
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Download Lang Repo
        run: |
          git clone "https://github.com/khadijahazward/ballerina-lang"
          cd ballerina-lang
          git checkout testFeature

      - name: Build Lang
        run: ./gradlew clean build -x test -x check publishToMavenLocal
        working-directory: ballerina-lang

      - name: Get Lang Version
        id: lang-version
        run: |
          LANG_VERSION=$((grep -w "version" | cut -d= -f2 | xargs) < ballerina-lang/gradle.properties)
          echo "::set-output name=version::$LANG_VERSION"

      - name: Update Lang Version
        run: |
          LANG_VERSION=${{ steps.lang-version.outputs.version }}
          perl -pi -e "s/^\s*ballerinaLangVersion=.*/ballerinaLangVersion=$LANG_VERSION/" gradle.properties

      - name: Verify Lang Version
        run: |
          LANG_VERSION=$((grep -w "ballerinaLangVersion" | cut -d= -f2 | xargs) < gradle.properties)
          echo "Lang Version: $LANG_VERSION"

      - name: Build Distribution
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
          githubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          ballerinaBotWorkflow: $ {{ secrets.BALLERINA_BOT_WORKFLOW }}
          TEST_MODE_ACTIVE: true
        run: ./gradlew clean build --stacktrace --scan --console=plain --no-daemon --continue -x project-api-tests:test -x test
